---
title: "TopoJSON choropleth map"
author: "TrantorM"
date: "21 Oktober 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The function [**addTopoJSONChoropleth()**](https://rawgit.com/TrantorM/leaflet.extras/master/docs/reference/topojson-choropleth.html) adds a topojson layer to leaflet in order to build a choropleth map. It is based on a [fork](https://github.com/TrantorM/leaflet-choropleth) of [timwis javascript leaflet-choropleth plugin ](https://github.com/timwis/leaflet-choropleth) and a [fork](https://github.com/TrantorM/leaflet.extras) of [bhaskarvk's htmlwidget leaflet.extra R-package](https://github.com/bhaskarvk/leaflet.extras). In both forks topojson support is added, but the function can still handle GeoJSON.

used packages:
```{r eval=FALSE}
install.packages('leaflet')
install.packages('readr')
install.packages('devtools')
devtools::install_github('TrantorM/leaflet.extras')
```


```{r }
library(leaflet)

R_topojsonObject_asString <- readr::read_file('https://rawgit.com/TrantorM/leaflet-choropleth/gh-pages/examples/basic_topo/crimes_by_district.topojson')

leaflet() %>% 
  setView(-75.14, 40, zoom = 11) %>%
  addTiles(urlTemplate = 'http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png',options = tileOptions(minZoom = 2, maxZoom = 18, tms = F)) %>%
  leaflet.extras::addTopoJSONChoropleth(
    R_topojsonObject_asString,
    valueProperty ='incidents',
    scale = c('white','red'), mode='q', steps = 5,
    popupProperty = JS("function(feature){return 'District ' + feature.properties.dist_num + '<br>' + feature.properties.incidents.toLocaleString() + ' incidents';}"),
    labelProperty = 'dist_num',
    color='#ffffff', weight=1, fillOpacity = 0.7
  )
```
